// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using API.Data.Import;
using API.Data.Import.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace API.Data.Import.Configurations
{
    public partial class ADRESSERConfiguration : IEntityTypeConfiguration<ADRESSER>
    {
        public void Configure(EntityTypeBuilder<ADRESSER> entity)
        {
            entity.HasKey(e => e.PK);

            entity.Property(e => e.Adress1)
                .HasMaxLength(8000)
                .IsUnicode(false);

            entity.Property(e => e.Aktiv).HasDefaultValueSql("((1))");

            entity.Property(e => e.Ort)
                .HasMaxLength(8000)
                .IsUnicode(false);

            entity.Property(e => e.Postnr)
                .HasMaxLength(8000)
                .IsUnicode(false);

            entity.HasOne(d => d.FK_ADRESSTYPNavigation)
                .WithMany(p => p.ADRESSER)
                .HasForeignKey(d => d.FK_ADRESSTYP)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ADRESSER_ADRESSTYP");

            entity.HasOne(d => d.FK_POSITIONERNavigation)
                .WithMany(p => p.ADRESSER)
                .HasForeignKey(d => d.FK_POSITIONER)
                .HasConstraintName("FK_ADRESSER_POSITIONER");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ADRESSER> entity);
    }
}
