// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using API.Data.Import;
using API.Data.Import.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace API.Data.Import.Configurations
{
    public partial class ARBETSPLATSERConfiguration : IEntityTypeConfiguration<ARBETSPLATSER>
    {
        public void Configure(EntityTypeBuilder<ARBETSPLATSER> entity)
        {
            entity.HasKey(e => e.PK);

            entity.HasIndex(e => e.FK_KUNDER, "_dta_index_ARBETSPLATSER_5_773577794__K3_1_2_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20_21_22_4364");

            entity.Property(e => e.Aktiv)
                .IsRequired()
                .HasDefaultValueSql("((1))");

            entity.Property(e => e.ArbetsplatsNamn)
                .HasMaxLength(8000)
                .IsUnicode(false);

            entity.HasOne(d => d.FK_ADRESSERNavigation)
                .WithMany(p => p.ARBETSPLATSER)
                .HasForeignKey(d => d.FK_ADRESSER)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ARBETSPLATSER_ADRESSER");

            entity.HasOne(d => d.FK_KUNDERNavigation)
                .WithMany(p => p.ARBETSPLATSER)
                .HasForeignKey(d => d.FK_KUNDER)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ARBETSPLATSER_KUNDER");

            entity.HasOne(d => d.FK_POSITIONERNavigation)
                .WithMany(p => p.ARBETSPLATSER)
                .HasForeignKey(d => d.FK_POSITIONER)
                .HasConstraintName("FK_ARBETSPLATSER_POSITIONER");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ARBETSPLATSER> entity);
    }
}
