// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using API.Data.Import;
using API.Data.Import.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace API.Data.Import.Configurations
{
    public partial class ARBETSPLATSER_AGAREConfiguration : IEntityTypeConfiguration<ARBETSPLATSER_AGARE>
    {
        public void Configure(EntityTypeBuilder<ARBETSPLATSER_AGARE> entity)
        {
            entity.HasKey(e => e.PK);

            entity.Property(e => e.FranDag).HasColumnType("datetime");

            entity.Property(e => e.SkapadAv)
                .HasMaxLength(8000)
                .IsUnicode(false);

            entity.Property(e => e.SkapadTidpunkt)
                .HasColumnType("datetime")
                .HasDefaultValueSql("(getdate())");

            entity.Property(e => e.UtfordTidpunkt).HasColumnType("datetime");

            entity.HasOne(d => d.FK_ADRESSER_GAMMAL_FAKTURERINGNavigation)
                .WithMany(p => p.ARBETSPLATSER_AGAREFK_ADRESSER_GAMMAL_FAKTURERINGNavigation)
                .HasForeignKey(d => d.FK_ADRESSER_GAMMAL_FAKTURERING)
                .HasConstraintName("FK_ARBETSPLATSER_AGARE_ADRESSER");

            entity.HasOne(d => d.FK_ADRESSER_NY_FAKTURERINGNavigation)
                .WithMany(p => p.ARBETSPLATSER_AGAREFK_ADRESSER_NY_FAKTURERINGNavigation)
                .HasForeignKey(d => d.FK_ADRESSER_NY_FAKTURERING)
                .HasConstraintName("FK_ARBETSPLATSER_AGARE_ADRESSER1");

            entity.HasOne(d => d.FK_ARBETSPLATSERNavigation)
                .WithMany(p => p.ARBETSPLATSER_AGARE)
                .HasForeignKey(d => d.FK_ARBETSPLATSER)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ARBETSPLATSER_AGARE_ARBETSPLATSER");

            entity.HasOne(d => d.FK_KUNDERNavigation)
                .WithMany(p => p.ARBETSPLATSER_AGARE)
                .HasForeignKey(d => d.FK_KUNDER)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ARBETSPLATSER_AGARE_KUNDER");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ARBETSPLATSER_AGARE> entity);
    }
}
