// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using API.Data.Import;
using API.Data.Import.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace API.Data.Import.Configurations
{
    public partial class KONTAKTER_ARBETSPLATSERConfiguration : IEntityTypeConfiguration<KONTAKTER_ARBETSPLATSER>
    {
        public void Configure(EntityTypeBuilder<KONTAKTER_ARBETSPLATSER> entity)
        {
            entity.HasKey(e => new { e.FK_KONTAKTER, e.FK_ARBETSPLATSER });

            entity.HasOne(d => d.FK_ARBETSPLATSERNavigation)
                .WithMany(p => p.KONTAKTER_ARBETSPLATSER)
                .HasForeignKey(d => d.FK_ARBETSPLATSER)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_KONTAKTER_ARBETSPLATSER_ARBETSPLATSER");

            entity.HasOne(d => d.FK_KONTAKTERNavigation)
                .WithMany(p => p.KONTAKTER_ARBETSPLATSER)
                .HasForeignKey(d => d.FK_KONTAKTER)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_KONTAKTER_ARBETSPLATSER_KONTAKTER");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<KONTAKTER_ARBETSPLATSER> entity);
    }
}
