// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using API.Data.Import;
using API.Data.Import.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace API.Data.Import.Configurations
{
    public partial class KUNDERConfiguration : IEntityTypeConfiguration<KUNDER>
    {
        public void Configure(EntityTypeBuilder<KUNDER> entity)
        {
            entity.HasKey(e => e.PK);

            entity.HasIndex(e => e.PK, "_dta_index_KUNDER_5_958626458__K1_8066");

            entity.Property(e => e.Aktiv)
                .IsRequired()
                .HasDefaultValueSql("((1))");

            entity.Property(e => e.KundNamn)
                .HasMaxLength(8000)
                .IsUnicode(false);

            entity.Property(e => e.KundNr)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.FK_ADRESSER_BESOKSADRESSNavigation)
                .WithMany(p => p.KUNDERFK_ADRESSER_BESOKSADRESSNavigation)
                .HasForeignKey(d => d.FK_ADRESSER_BESOKSADRESS)
                .HasConstraintName("FK_KUNDER_ADRESSER1");

            entity.HasOne(d => d.FK_ADRESSER_FAKTURAADRESSNavigation)
                .WithMany(p => p.KUNDERFK_ADRESSER_FAKTURAADRESSNavigation)
                .HasForeignKey(d => d.FK_ADRESSER_FAKTURAADRESS)
                .HasConstraintName("FK_KUNDER_ADRESSER");

            entity.HasOne(d => d.FK_BETALARENavigation)
                .WithMany(p => p.InverseFK_BETALARENavigation)
                .HasForeignKey(d => d.FK_BETALARE)
                .HasConstraintName("FK_KUNDER_KUNDER");

            entity.HasOne(d => d.FK_ENTREPRENADNavigation)
                .WithMany(p => p.InverseFK_ENTREPRENADNavigation)
                .HasForeignKey(d => d.FK_ENTREPRENAD)
                .HasConstraintName("FK_KUNDER_ENTREPRENAD");

            entity.HasOne(d => d.FK_KONCERNNavigation)
                .WithMany(p => p.InverseFK_KONCERNNavigation)
                .HasForeignKey(d => d.FK_KONCERN)
                .HasConstraintName("FK_KUNDER_KUNDER1");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<KUNDER> entity);
    }
}
