// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using API.Data.Import;
using API.Data.Import.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace API.Data.Import.Configurations
{
    public partial class PERSONERConfiguration : IEntityTypeConfiguration<PERSONER>
    {
        public void Configure(EntityTypeBuilder<PERSONER> entity)
        {
            entity.HasKey(e => e.PK);

            entity.Property(e => e.PersonNamn)
                .HasMaxLength(8000)
                .IsUnicode(false);

            entity.Property(e => e.Personnummer)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.FK_ADRESSERNavigation)
                .WithMany(p => p.PERSONER)
                .HasForeignKey(d => d.FK_ADRESSER)
                .HasConstraintName("FK_PERSONER_ADRESSER");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PERSONER> entity);
    }
}
