// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using API.Data.Import;
using API.Data.Import.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace API.Data.Import.Configurations
{
    public partial class POSITIONERConfiguration : IEntityTypeConfiguration<POSITIONER>
    {
        public void Configure(EntityTypeBuilder<POSITIONER> entity)
        {
            entity.HasKey(e => e.PK);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<POSITIONER> entity);
    }
}
