// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using API.Data.Import;
using API.Data.Import.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace API.Data.Import.Configurations
{
    public partial class VALIDERING_GRUPPConfiguration : IEntityTypeConfiguration<VALIDERING_GRUPP>
    {
        public void Configure(EntityTypeBuilder<VALIDERING_GRUPP> entity)
        {
            entity.HasKey(e => e.PK);

            entity.Property(e => e.GruppNamn)
                .HasMaxLength(8000)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VALIDERING_GRUPP> entity);
    }
}
