// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using API.Data.Import;
using API.Data.Import.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace API.Data.Import.Configurations
{
    public partial class VALIDERING_KUNDERConfiguration : IEntityTypeConfiguration<VALIDERING_KUNDER>
    {
        public void Configure(EntityTypeBuilder<VALIDERING_KUNDER> entity)
        {
            entity.HasKey(e => e.PK);

            entity.HasOne(d => d.FK_KUNDERNavigation)
                .WithMany(p => p.VALIDERING_KUNDER)
                .HasForeignKey(d => d.FK_KUNDER)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VALIDERING_KUNDER_KUNDER");

            entity.HasOne(d => d.FK_VALIDERINGNavigation)
                .WithMany(p => p.VALIDERING_KUNDER)
                .HasForeignKey(d => d.FK_VALIDERING)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VALIDERING_KUNDER_VALIDERING");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VALIDERING_KUNDER> entity);
    }
}
