// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using API.Data.Import;
using API.Data.Import.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace API.Data.Import.Configurations
{
    public partial class VALIDERINGConfiguration : IEntityTypeConfiguration<VALIDERING>
    {
        public void Configure(EntityTypeBuilder<VALIDERING> entity)
        {
            entity.HasKey(e => e.PK);

            entity.Property(e => e.Namn)
                .HasMaxLength(8000)
                .IsUnicode(false);

            entity.HasOne(d => d.FK_GRUPPNavigation)
                .WithMany(p => p.VALIDERING)
                .HasForeignKey(d => d.FK_GRUPP)
                .HasConstraintName("FK_VALIDERING_VALIDERING_GRUPP");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VALIDERING> entity);
    }
}
