// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using API.Data.Import;
using API.Data.Import.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace API.Data.Import.Configurations
{
    public partial class VALIDERING_REGELConfiguration : IEntityTypeConfiguration<VALIDERING_REGEL>
    {
        public void Configure(EntityTypeBuilder<VALIDERING_REGEL> entity)
        {
            entity.HasKey(e => e.PK);

            entity.Property(e => e.EntitetsNamn)
                .HasMaxLength(8000)
                .IsUnicode(false);

            entity.Property(e => e.Felmeddelande)
                .HasMaxLength(8000)
                .IsUnicode(false);

            entity.Property(e => e.PropertyNamn)
                .HasMaxLength(8000)
                .IsUnicode(false);

            entity.Property(e => e.RegexPattern)
                .HasMaxLength(8000)
                .IsUnicode(false);

            entity.Property(e => e.VardeAlfanumeriskt)
                .HasMaxLength(8000)
                .IsUnicode(false);

            entity.Property(e => e.VardeDatum).HasColumnType("datetime");

            entity.HasOne(d => d.FK_REGELNavigation)
                .WithMany(p => p.InverseFK_REGELNavigation)
                .HasForeignKey(d => d.FK_REGEL)
                .HasConstraintName("FK_VALIDERING_REGEL_VALIDERING_REGEL");

            entity.HasOne(d => d.FK_VALIDERINGNavigation)
                .WithMany(p => p.VALIDERING_REGEL)
                .HasForeignKey(d => d.FK_VALIDERING)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VALIDERING_REGEL_VALIDERING");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VALIDERING_REGEL> entity);
    }
}
