namespace API.Enums
{
    public enum EnumValidationOperation
    {
        Equals,
        DoesNotEqual,
        GreaterThan,
        GreaterThanOrEqual,
        LesserThan,
        LesserThanOrEqual,
        MatchesRegex,
        IsNull,
        IsNotNull,
        AnnanRegel,
        AnnanRegelFleraAny,
        AnnanRegelFleraAll,
        Contains,
        DoesNotContain,
        DoesNotMatchRegex,
        LongerThan,
        LongerThanOrEqual,
        ShorterThan,
        ShorterThanOrEqual,
        StartsWith,
        DoesNotStartWith,
        EndsWith,
        DoesNotEndWith,
        Count,
        NotCount,
        CountIsMoreThan,
        CountIsMoreThanOrEqual,
        CountIsLessThan,
        CountIsLessThanOrEqual
    }
}
