// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace API.Entities
{
    public partial class Adresstyp
    {
        public Adresstyp()
        {
            Adresser = new HashSet<Adresser>();
        }

        public int Pk { get; set; }
        public string? AdresstypNamn { get; set; }
        public bool? VisaPaWeb { get; set; }

        public virtual ICollection<Adresser> Adresser { get; set; }
    }
}