// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace API.Entities
{
    public partial class Positioner
    {
        public Positioner()
        {
            Adresser = new HashSet<Adresser>();
            Arbetsplatser = new HashSet<Arbetsplatser>();
        }

        public int Pk { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public double? Xkoord { get; set; }
        public double? Ykoord { get; set; }
        public string? ReverseGeocodeResult { get; set; }

        public virtual ICollection<Adresser> Adresser { get; set; }
        public virtual ICollection<Arbetsplatser> Arbetsplatser { get; set; }
    }
}