// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace API.Data.Import.Entities
{
    public partial class ADRESSTYP
    {
        public ADRESSTYP()
        {
            ADRESSER = new HashSet<ADRESSER>();
        }

        public int PK { get; set; }
        public string? AdresstypNamn { get; set; }

        public virtual ICollection<ADRESSER> ADRESSER { get; set; }
    }
}