// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace API.Data.Import.Entities
{
    public partial class ADRESSER
    {
        public ADRESSER()
        {
            ARBETSPLATSER = new HashSet<ARBETSPLATSER>();
            KUNDERFK_ADRESSER_BESOKSADRESSNavigation = new HashSet<KUNDER>();
            KUNDERFK_ADRESSER_FAKTURAADRESSNavigation = new HashSet<KUNDER>();
        }

        public int PK { get; set; }
        public bool? Aktiv { get; set; }
        public int FK_ADRESSTYP { get; set; }
        public int? FK_POSITIONER { get; set; }
        public int? FK_LANDER { get; set; }
        public string? Namn { get; set; }
        public string? CO { get; set; }
        public string? Adress1 { get; set; }
        public string? Adress2 { get; set; }
        public string? Zon { get; set; }
        public string? Postnr { get; set; }
        public string? Ort { get; set; }
        public string? Kontakt { get; set; }
        public string? Epost { get; set; }
        public string? Telefon1 { get; set; }
        public string? Telefon2 { get; set; }
        public string? Telefon3 { get; set; }
        public string? Mobiltelefon { get; set; }
        public string? Fax { get; set; }
        public string? Vagbeskrivning { get; set; }
        public string? Referens { get; set; }
        public string? Id { get; set; }
        public int? FK_ZON { get; set; }
        public string? Lastinfo { get; set; }
        public string? Lossinfo { get; set; }
        public string? PallregNummer { get; set; }
        public DateTime? Slottid { get; set; }
        public string? InternInformation { get; set; }
        public string? KommunKod { get; set; }
        public string? LagerStalleNr { get; set; }
        public DateTime? SlottidSlut { get; set; }
        public string? SiloId { get; set; }
        public string? Framkomlighet { get; set; }
        public string? CfarNr { get; set; }

        public virtual ADRESSTYP FK_ADRESSTYPNavigation { get; set; } = null!;
        public virtual POSITIONER? FK_POSITIONERNavigation { get; set; }
        public virtual ICollection<ARBETSPLATSER> ARBETSPLATSER { get; set; }
        public virtual ICollection<KUNDER> KUNDERFK_ADRESSER_BESOKSADRESSNavigation { get; set; }
        public virtual ICollection<KUNDER> KUNDERFK_ADRESSER_FAKTURAADRESSNavigation { get; set; }
    }
}