// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace API.Data.Import.Entities
{
    public partial class ADRESSER
    {
        public ADRESSER()
        {
            ARBETSPLATSER = new HashSet<ARBETSPLATSER>();
            KUNDERFK_ADRESSER_BESOKSADRESSNavigation = new HashSet<KUNDER>();
            KUNDERFK_ADRESSER_FAKTURAADRESSNavigation = new HashSet<KUNDER>();
            PERSONER = new HashSet<PERSONER>();
        }

        public int PK { get; set; }
        public bool? Aktiv { get; set; }
        public int FK_ADRESSTYP { get; set; }
        public int? FK_POSITIONER { get; set; }
        public int? FK_LANDER { get; set; }
        public string? Adress1 { get; set; }
        public string? Postnr { get; set; }
        public string? Ort { get; set; }
        public int? FK_ZON { get; set; }

        public virtual ADRESSTYP FK_ADRESSTYPNavigation { get; set; } = null!;
        public virtual POSITIONER? FK_POSITIONERNavigation { get; set; }
        public virtual ICollection<ARBETSPLATSER> ARBETSPLATSER { get; set; }
        public virtual ICollection<KUNDER> KUNDERFK_ADRESSER_BESOKSADRESSNavigation { get; set; }
        public virtual ICollection<KUNDER> KUNDERFK_ADRESSER_FAKTURAADRESSNavigation { get; set; }
        public virtual ICollection<PERSONER> PERSONER { get; set; }
    }
}