// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace API.Data.Import.Entities
{
    public partial class ARBETSPLATSER_AGARE
    {
        public int PK { get; set; }
        public int FK_ARBETSPLATSER { get; set; }
        public int FK_KUNDER { get; set; }
        public DateTime FranDag { get; set; }
        public DateTime? UtfordTidpunkt { get; set; }
        public string? SkapadAv { get; set; }
        public DateTime SkapadTidpunkt { get; set; }
        public int? FK_ADRESSER_NY_FAKTURERING { get; set; }
        public int? FK_ADRESSER_GAMMAL_FAKTURERING { get; set; }

        public virtual ADRESSER? FK_ADRESSER_GAMMAL_FAKTURERINGNavigation { get; set; }
        public virtual ADRESSER? FK_ADRESSER_NY_FAKTURERINGNavigation { get; set; }
        public virtual ARBETSPLATSER FK_ARBETSPLATSERNavigation { get; set; } = null!;
        public virtual KUNDER FK_KUNDERNavigation { get; set; } = null!;
    }
}