// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace API.Data.Import.Entities
{
    public partial class KONTAKTER_ARBETSPLATSER
    {
        public int FK_KONTAKTER { get; set; }
        public int FK_ARBETSPLATSER { get; set; }

        public virtual ARBETSPLATSER FK_ARBETSPLATSERNavigation { get; set; } = null!;
        public virtual KONTAKTER FK_KONTAKTERNavigation { get; set; } = null!;
    }
}