// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace API.Data.Import.Entities
{
    public partial class KONTAKTER
    {
        public KONTAKTER()
        {
            ARBETSPLATSER = new HashSet<ARBETSPLATSER>();
            KONTAKTER_ARBETSPLATSER = new HashSet<KONTAKTER_ARBETSPLATSER>();
        }

        public int PK { get; set; }
        public int? FK_PERSONER { get; set; }
        public int FK_KUNDER { get; set; }
        public int? FK_LITTERA { get; set; }
        public string? KontaktNamn { get; set; }
        public string? Avdelning { get; set; }
        public bool? Aktiv { get; set; }
        public string? GDPR_Raderad { get; set; }

        public virtual KUNDER FK_KUNDERNavigation { get; set; } = null!;
        public virtual PERSONER? FK_PERSONERNavigation { get; set; }
        public virtual ICollection<ARBETSPLATSER> ARBETSPLATSER { get; set; }
        public virtual ICollection<KONTAKTER_ARBETSPLATSER> KONTAKTER_ARBETSPLATSER { get; set; }
    }
}