// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace API.Data.Import.Entities
{
    public partial class PERSONER
    {
        public PERSONER()
        {
            KONTAKTER = new HashSet<KONTAKTER>();
        }

        public int PK { get; set; }
        public int? FK_ADRESSER { get; set; }
        public int? FK_BILDER { get; set; }
        public string? Personnummer { get; set; }
        public string? PersonNamn { get; set; }

        public virtual ADRESSER? FK_ADRESSERNavigation { get; set; }
        public virtual ICollection<KONTAKTER> KONTAKTER { get; set; }
    }
}