// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace API.Data.Import.Entities
{
    public partial class VALIDERING_REGEL
    {
        public VALIDERING_REGEL()
        {
            InverseFK_REGELNavigation = new HashSet<VALIDERING_REGEL>();
        }

        public int PK { get; set; }
        public int FK_VALIDERING { get; set; }
        public string EntitetsNamn { get; set; } = null!;
        public string PropertyNamn { get; set; } = null!;
        public int FK_EnumOperation { get; set; }
        public string? Felmeddelande { get; set; }
        public double? VardeNumeriskt { get; set; }
        public string? VardeAlfanumeriskt { get; set; }
        public DateTime? VardeDatum { get; set; }
        public int? FK_Entitet { get; set; }
        public string? RegexPattern { get; set; }
        public bool? VardeBoolean { get; set; }
        public int? FK_REGEL { get; set; }
        public bool AllowNull { get; set; }

        public virtual VALIDERING_REGEL? FK_REGELNavigation { get; set; }
        public virtual VALIDERING FK_VALIDERINGNavigation { get; set; } = null!;
        public virtual ICollection<VALIDERING_REGEL> InverseFK_REGELNavigation { get; set; }
    }
}