// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace API.Data.Import.Entities
{
    public partial class VALIDERING_KUNDER
    {
        public int PK { get; set; }
        public int FK_VALIDERING { get; set; }
        public int FK_KUNDER { get; set; }

        public virtual KUNDER FK_KUNDERNavigation { get; set; } = null!;
        public virtual VALIDERING FK_VALIDERINGNavigation { get; set; } = null!;
    }
}