// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace API.Data.Import.Entities
{
    public partial class VALIDERING_GRUPP
    {
        public VALIDERING_GRUPP()
        {
            VALIDERING = new HashSet<VALIDERING>();
        }

        public int PK { get; set; }
        public string GruppNamn { get; set; } = null!;

        public virtual ICollection<VALIDERING> VALIDERING { get; set; }
    }
}