// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace API.Data.Import.Entities
{
    public partial class VERKSAMHETER
    {
        public VERKSAMHETER()
        {
            VALIDERING_VERKSAMHETER = new HashSet<VALIDERING_VERKSAMHETER>();
        }

        public int PK { get; set; }
        public bool? Aktiv { get; set; }
        public int FK_AFFARSOMRADEN { get; set; }
        public string? VerksamhetNamn { get; set; }
        public int? FK_ARTIKLAR_Tjanst { get; set; }
        public int? FK_ZONER_AVS { get; set; }
        public int? FK_ZONER_MOT { get; set; }
        public int? FK_ARTIKLAR_Lastning { get; set; }
        public int? FK_ARTIKLAR_Lossning { get; set; }
        public int? FK_RESURSKATEGORI { get; set; }

        public virtual ICollection<VALIDERING_VERKSAMHETER> VALIDERING_VERKSAMHETER { get; set; }
    }
}