// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using API.Data.Import.Configurations;
using API.Data.Import.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using System;
using System.Collections.Generic;
#nullable enable

namespace API.Data.Import
{
    public partial class ImportDbContext : DbContext
    {
        public ImportDbContext(DbContextOptions<ImportDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<ADRESSER> ADRESSER { get; set; } = null!;
        public virtual DbSet<ADRESSTYP> ADRESSTYP { get; set; } = null!;
        public virtual DbSet<ARBETSPLATSER> ARBETSPLATSER { get; set; } = null!;
        public virtual DbSet<KONTAKTER> KONTAKTER { get; set; } = null!;
        public virtual DbSet<KUNDER> KUNDER { get; set; } = null!;
        public virtual DbSet<PERSONER> PERSONER { get; set; } = null!;
        public virtual DbSet<POSITIONER> POSITIONER { get; set; } = null!;
        public virtual DbSet<VALIDERING> VALIDERING { get; set; } = null!;
        public virtual DbSet<VALIDERING_GRUPP> VALIDERING_GRUPP { get; set; } = null!;
        public virtual DbSet<VALIDERING_KUNDER> VALIDERING_KUNDER { get; set; } = null!;
        public virtual DbSet<VALIDERING_REGEL> VALIDERING_REGEL { get; set; } = null!;
        public virtual DbSet<VALIDERING_VERKSAMHETER> VALIDERING_VERKSAMHETER { get; set; } = null!;
        public virtual DbSet<VERKSAMHETER> VERKSAMHETER { get; set; } = null!;

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.UseCollation("Finnish_Swedish_CI_AS");

            modelBuilder.ApplyConfiguration(new Configurations.ADRESSERConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ADRESSTYPConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ARBETSPLATSERConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.KONTAKTERConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.KUNDERConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.PERSONERConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.POSITIONERConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.VALIDERINGConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.VALIDERING_GRUPPConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.VALIDERING_KUNDERConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.VALIDERING_REGELConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.VALIDERING_VERKSAMHETERConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.VERKSAMHETERConfiguration());
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
