// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using API.Data.Import.Configurations;
using API.Data.Import.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using System;
using System.Collections.Generic;
#nullable enable

namespace API.Data.Import
{
    public partial class ImportDbContext : DbContext
    {
        public ImportDbContext(DbContextOptions<ImportDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<ADRESSER> ADRESSER { get; set; } = null!;
        public virtual DbSet<ADRESSTYP> ADRESSTYP { get; set; } = null!;
        public virtual DbSet<ARBETSPLATSER> ARBETSPLATSER { get; set; } = null!;
        public virtual DbSet<KUNDER> KUNDER { get; set; } = null!;
        public virtual DbSet<POSITIONER> POSITIONER { get; set; } = null!;

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.UseCollation("Finnish_Swedish_CI_AS");

            modelBuilder.ApplyConfiguration(new Configurations.ADRESSERConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ADRESSTYPConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ARBETSPLATSERConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.KUNDERConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.POSITIONERConfiguration());
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
